# Generated by Django 5.2.5 on 2025-11-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0002_remove_profile_language_remove_profile_metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar_url',
            new_name='avatar_id',
        ),
    ]
