# Generated by Django 5.2.5 on 2025-09-02 15:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=200)),
                ('objective', models.TextField(default='')),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), db_index=True, default=list, size=None)),
                ('Collection_contents', models.JSONField(default=dict)),
            ],
        ),
    ]
