# Generated by Django 5.2.5 on 2025-11-18 03:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExplorationState',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('interaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('card_is_checkpoint', models.BooleanField(default=False)),
                ('linked_skill_id', models.CharField(blank=True, max_length=255, null=True)),
                ('classifier_model_id', models.CharField(blank=True, max_length=255, null=True)),
                ('solicit_answer_details', models.BooleanField(default=False)),
                ('inapplicable_skill_misconception_ids', models.JSONField(blank=True, default=list)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exploration State',
                'verbose_name_plural': 'Exploration States',
                'ordering': ['exploration', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('time_limit', models.DurationField(blank=True, help_text="Thời gian tối đa cho phép (ví dụ: '00:30:00' cho 30 phút, '01:00:00' cho 1 tiếng)", null=True, verbose_name='Thời lượng làm bài')),
                ('time_open', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian mở')),
                ('time_close', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đóng (hạn chót)')),
            ],
            options={
                'verbose_name': 'Bài trắc nghiệm',
                'verbose_name_plural': 'Các bài trắc nghiệm',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=16, null=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, help_text='Timestamp when the course was last published.', null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title, auto-generated if blank.', max_length=255, null=True, unique=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='courses', to='content.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_owned', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='content.subject')),
                ('tags', models.ManyToManyField(blank=True, related_name='courses', to='content.tag')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Exploration',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='vi', max_length=8)),
                ('init_state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('param_changes', models.JSONField(blank=True, default=list)),
                ('param_specs', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('blurb', models.TextField(blank=True, null=True)),
                ('author_notes', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explorations', to='content.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explorations_owned', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='explorations', to='content.tag')),
            ],
            options={
                'verbose_name': 'Exploration',
                'verbose_name_plural': 'Explorations',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='solution', serialize=False, to='content.explorationstate')),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('answer_is_exclusive', models.BooleanField(default=False)),
                ('solution_explanation_html', models.TextField(blank=True, null=True)),
                ('solution_explanation_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solution',
            },
        ),
        migrations.AddField(
            model_name='explorationstate',
            name='exploration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='content.exploration'),
        ),
        migrations.CreateModel(
            name='AnswerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_index', models.IntegerField()),
                ('outcome_dest', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome_dest_if_really_stuck', models.CharField(blank=True, max_length=255, null=True)),
                ('refresher_exploration_id', models.CharField(blank=True, max_length=255, null=True)),
                ('missing_prerequisite_skill_id', models.CharField(blank=True, max_length=255, null=True)),
                ('labelled_as_correct', models.BooleanField(default=False)),
                ('outcome_feedback_html', models.TextField(blank=True, null=True)),
                ('outcome_feedback_text', models.TextField(blank=True, null=True)),
                ('training_data', models.JSONField(blank=True, default=list)),
                ('tagged_skill_misconception_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_groups', to='content.explorationstate')),
            ],
            options={
                'verbose_name': 'Answer Group',
                'ordering': ['state', 'group_index'],
                'unique_together': {('state', 'group_index')},
            },
        ),
        migrations.CreateModel(
            name='ExplorationTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_type', models.CharField(default='default', max_length=255)),
                ('condition_data_raw', models.JSONField(blank=True, default=dict)),
                ('feedback_html', models.TextField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transitions', to='content.explorationstate')),
            ],
            options={
                'verbose_name': 'Exploration Transition',
                'verbose_name_plural': 'Exploration Transitions',
                'ordering': ['from_state'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('content_type', models.CharField(choices=[('lesson', 'Lesson'), ('exploration', 'Exploration'), ('exercise', 'Exercise'), ('video', 'video')], default='lesson', max_length=32)),
                ('published', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.module')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('multiple_choice_single', 'Trắc nghiệm - Chọn 1'), ('multiple_choice_multi', 'Trắc nghiệm - Chọn nhiều'), ('true_false', 'Đúng / Sai'), ('short_answer', 'Trả lời ngắn'), ('fill_in_the_blank', 'Điền vào chỗ trống'), ('matching', 'Nối cặp'), ('essay', 'Tự luận')], default='multiple_choice_single', max_length=50)),
                ('prompt', models.JSONField(blank=True, default=dict, help_text="Nội dung câu hỏi (e.g., {'text': '...', 'image_url': '...'})")),
                ('answer_payload', models.JSONField(blank=True, default=dict, help_text="Cấu hình đáp án, tùy thuộc vào 'type'")),
                ('hint', models.JSONField(blank=True, default=dict, help_text='Gợi ý hoặc giải thích đáp án')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.quiz')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Các câu hỏi',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('quiz', 'Quiz'), ('exploration_ref', 'Exploration Reference'), ('pdf', 'PDF Document'), ('docx', 'Word Document'), ('file', 'File')], max_length=32)),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('payload', models.JSONField(default=dict)),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='content.lesson')),
                ('quiz_ref', models.ForeignKey(blank=True, help_text="Tham chiếu đến một Quiz nếu type='quiz'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='content.quiz')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hint_index', models.IntegerField()),
                ('hint_content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hint_html', models.TextField(blank=True, null=True)),
                ('hint_text', models.TextField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='content.explorationstate')),
            ],
            options={
                'verbose_name': 'Hint',
                'ordering': ['state', 'hint_index'],
                'unique_together': {('state', 'hint_index')},
            },
        ),
        migrations.CreateModel(
            name='InteractionCustomizationArg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('arg_name', models.CharField(max_length=255)),
                ('arg_value_json', models.JSONField(default=dict)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_args', to='content.explorationstate')),
            ],
            options={
                'verbose_name': 'Interaction Argument',
                'unique_together': {('state', 'arg_name')},
            },
        ),
        migrations.CreateModel(
            name='RuleSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_index', models.IntegerField()),
                ('rule_type', models.CharField(max_length=255)),
                ('inputs_json', models.JSONField(default=dict)),
                ('answer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_specs', to='content.answergroup')),
            ],
            options={
                'verbose_name': 'Rule Spec',
                'ordering': ['answer_group', 'rule_index'],
                'unique_together': {('answer_group', 'rule_index')},
            },
        ),
        migrations.CreateModel(
            name='StateMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('media_index', models.IntegerField()),
                ('tag', models.CharField(max_length=255)),
                ('attrs', models.JSONField(default=dict)),
                ('alt', models.TextField(blank=True, null=True)),
                ('filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('math_value', models.TextField(blank=True, null=True)),
                ('outer_html', models.TextField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='content.explorationstate')),
            ],
            options={
                'verbose_name': 'State Media',
                'ordering': ['state', 'media_index'],
                'unique_together': {('state', 'media_index')},
            },
        ),
    ]
