# Generated by Django 5.2.5 on 2025-11-16 06:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_category_tag_course_categories_course_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('time_limit', models.DurationField(blank=True, help_text="Thời gian tối đa cho phép (ví dụ: '00:30:00' cho 30 phút, '01:00:00' cho 1 tiếng)", null=True, verbose_name='Thời lượng làm bài')),
                ('time_open', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian mở')),
                ('time_close', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đóng (hạn chót)')),
            ],
            options={
                'verbose_name': 'Bài trắc nghiệm',
                'verbose_name_plural': 'Các bài trắc nghiệm',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='solution', serialize=False, to='content.explorationstate')),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('answer_is_exclusive', models.BooleanField(default=False)),
                ('solution_explanation_html', models.TextField(blank=True, null=True)),
                ('solution_explanation_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solution',
            },
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='lesson_version',
        ),
        migrations.AlterModelOptions(
            name='exploration',
            options={'ordering': ['title'], 'verbose_name': 'Exploration', 'verbose_name_plural': 'Explorations'},
        ),
        migrations.AlterModelOptions(
            name='explorationstate',
            options={'ordering': ['exploration', 'name'], 'verbose_name': 'Exploration State', 'verbose_name_plural': 'Exploration States'},
        ),
        migrations.AlterModelOptions(
            name='explorationtransition',
            options={'ordering': ['from_state'], 'verbose_name': 'Exploration Transition', 'verbose_name_plural': 'Exploration Transitions'},
        ),
        migrations.RemoveField(
            model_name='explorationstate',
            name='content',
        ),
        migrations.RemoveField(
            model_name='explorationstate',
            name='interaction',
        ),
        migrations.RemoveField(
            model_name='explorationtransition',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='explorationtransition',
            name='exploration',
        ),
        migrations.RemoveField(
            model_name='explorationtransition',
            name='to_state',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the course was last published.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title, auto-generated if blank.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exploration',
            name='author_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploration',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploration',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explorations', to='content.category'),
        ),
        migrations.AddField(
            model_name='exploration',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploration',
            name='init_state_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exploration',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploration',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exploration',
            name='param_changes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exploration',
            name='param_specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exploration',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='explorations', to='content.tag'),
        ),
        migrations.AddField(
            model_name='exploration',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explorationstate',
            name='card_is_checkpoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='explorationstate',
            name='classifier_model_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='explorationstate',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explorationstate',
            name='content_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='explorationstate',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explorationstate',
            name='inapplicable_skill_misconception_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='explorationstate',
            name='interaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='explorationstate',
            name='linked_skill_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='explorationstate',
            name='solicit_answer_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='explorationtransition',
            name='condition_data_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='explorationtransition',
            name='condition_type',
            field=models.CharField(default='standard', max_length=255),
        ),
        migrations.AddField(
            model_name='explorationtransition',
            name='feedback_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explorationtransition',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explorationtransition',
            name='to_state_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('quiz', 'Quiz'), ('exploration_ref', 'Exploration Reference'), ('pdf', 'PDF Document'), ('docx', 'Word Document'), ('file', 'File')], max_length=32),
        ),
        migrations.AlterField(
            model_name='exploration',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='explorationstate',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('exploration', 'Exploration'), ('exercise', 'Exercise'), ('video', 'video')], default='lesson', max_length=32),
        ),
        migrations.CreateModel(
            name='AnswerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_index', models.IntegerField()),
                ('outcome_dest', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome_dest_if_really_stuck', models.CharField(blank=True, max_length=255, null=True)),
                ('refresher_exploration_id', models.CharField(blank=True, max_length=255, null=True)),
                ('missing_prerequisite_skill_id', models.CharField(blank=True, max_length=255, null=True)),
                ('labelled_as_correct', models.BooleanField(default=False)),
                ('outcome_feedback_html', models.TextField(blank=True, null=True)),
                ('outcome_feedback_text', models.TextField(blank=True, null=True)),
                ('training_data', models.JSONField(blank=True, default=list)),
                ('tagged_skill_misconception_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_groups', to='content.explorationstate')),
            ],
            options={
                'verbose_name': 'Answer Group',
                'ordering': ['state', 'group_index'],
                'unique_together': {('state', 'group_index')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hint_index', models.IntegerField()),
                ('hint_content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hint_html', models.TextField(blank=True, null=True)),
                ('hint_text', models.TextField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='content.explorationstate')),
            ],
            options={
                'verbose_name': 'Hint',
                'ordering': ['state', 'hint_index'],
                'unique_together': {('state', 'hint_index')},
            },
        ),
        migrations.CreateModel(
            name='InteractionCustomizationArg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('arg_name', models.CharField(max_length=255)),
                ('arg_value_json', models.JSONField(default=dict)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_args', to='content.explorationstate')),
            ],
            options={
                'verbose_name': 'Interaction Argument',
                'unique_together': {('state', 'arg_name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('multiple_choice_single', 'Trắc nghiệm - Chọn 1'), ('multiple_choice_multi', 'Trắc nghiệm - Chọn nhiều'), ('true_false', 'Đúng / Sai'), ('short_answer', 'Trả lời ngắn'), ('fill_in_the_blank', 'Điền vào chỗ trống'), ('matching', 'Nối cặp'), ('essay', 'Tự luận')], default='multiple_choice_single', max_length=50)),
                ('prompt', models.JSONField(blank=True, default=dict, help_text="Nội dung câu hỏi (e.g., {'text': '...', 'image_url': '...'})")),
                ('answer_payload', models.JSONField(blank=True, default=dict, help_text="Cấu hình đáp án, tùy thuộc vào 'type'")),
                ('hint', models.JSONField(blank=True, default=dict, help_text='Gợi ý hoặc giải thích đáp án')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.quiz')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Các câu hỏi',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RuleSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_index', models.IntegerField()),
                ('rule_type', models.CharField(max_length=255)),
                ('inputs_json', models.JSONField(default=dict)),
                ('answer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_specs', to='content.answergroup')),
            ],
            options={
                'verbose_name': 'Rule Spec',
                'ordering': ['answer_group', 'rule_index'],
                'unique_together': {('answer_group', 'rule_index')},
            },
        ),
        migrations.CreateModel(
            name='StateMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('media_index', models.IntegerField()),
                ('tag', models.CharField(max_length=255)),
                ('attrs', models.JSONField(default=dict)),
                ('alt', models.TextField(blank=True, null=True)),
                ('filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('math_value', models.TextField(blank=True, null=True)),
                ('outer_html', models.TextField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='content.explorationstate')),
            ],
            options={
                'verbose_name': 'State Media',
                'ordering': ['state', 'media_index'],
                'unique_together': {('state', 'media_index')},
            },
        ),
        migrations.DeleteModel(
            name='LessonVersion',
        ),
    ]
