# Generated by Django 5.2.5 on 2025-11-22 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_course_created_at_course_updated_at'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='quiz_ref',
            field=models.ForeignKey(blank=True, help_text="Tham chiếu đến một Quiz nếu type='quiz'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='quiz.quiz'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
