# Generated by Django 5.2.5 on 2025-11-17 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_quiz_solution_remove_contentblock_lesson_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='quiz_ref',
            field=models.ForeignKey(blank=True, help_text="Tham chiếu đến một Quiz nếu type='quiz'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='content.quiz'),
        ),
        migrations.AlterField(
            model_name='explorationtransition',
            name='condition_type',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
