# Generated by Django 5.2.5 on 2025-11-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contentblock_quiz_ref_delete_question_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interactioncustomizationarg',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='interactioncustomizationarg',
            name='state',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='state',
        ),
        migrations.AlterUniqueTogether(
            name='statemedia',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statemedia',
            name='state',
        ),
        migrations.AlterModelOptions(
            name='answergroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exploration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='explorationstate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rulespec',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='answergroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hint',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rulespec',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='published',
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('quiz', 'Quiz'), ('pdf', 'PDF Document'), ('docx', 'Word Document'), ('file', 'File')], max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='ExplorationTransition',
        ),
        migrations.DeleteModel(
            name='InteractionCustomizationArg',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='StateMedia',
        ),
    ]
