# Generated by Django 5.2.5 on 2025-11-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_interactioncustomizationarg_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={},
        ),
    ]
