# Generated by Django 5.2.5 on 2025-11-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_hint_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulespec',
            name='answer_group',
        ),
        migrations.RemoveField(
            model_name='exploration',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exploration',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='exploration',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='explorationstate',
            name='exploration',
        ),
        migrations.RemoveField(
            model_name='hint',
            name='state',
        ),
        migrations.DeleteModel(
            name='AnswerGroup',
        ),
        migrations.DeleteModel(
            name='RuleSpec',
        ),
        migrations.DeleteModel(
            name='Exploration',
        ),
        migrations.DeleteModel(
            name='ExplorationState',
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
    ]
