# Generated by Django 5.2.5 on 2025-12-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_rulespec_answer_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='title',
            field=models.CharField(blank=True, help_text='Tiêu đề hiển thị trên mục lục (VD: Video hướng dẫn)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('rich_text', 'Rich Text'), ('video', 'Video'), ('pdf', 'PDF Document'), ('docx', 'Word Document'), ('file', 'File'), ('quiz', 'Quiz')], max_length=32),
        ),
    ]
