# Generated by Django 5.2.5 on 2025-12-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contentblock_title_alter_contentblock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('rich_text', 'Rich Text'), ('video', 'Video'), ('pdf', 'PDF Document'), ('docx', 'Word Document'), ('file', 'File'), ('quiz', 'Quiz'), ('audio', 'Audio')], max_length=32),
        ),
    ]
