# Generated by Django 5.2.5 on 2025-12-09 13:17

import core.custom_storages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_contentblock_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='VND', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=core.custom_storages.PublicMediaStorage(), upload_to='course_thumbnails/'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['published', 'grade'], name='content_cou_publish_d3fc74_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner'], name='content_cou_owner_i_ec36f9_idx'),
        ),
    ]
