# Generated by Django 5.2.5 on 2025-12-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_course_options_course_currency_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Thời lượng tính bằng giây'),
        ),
    ]
