# Generated by Django 5.2.5 on 2025-12-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_enrollment_options_enrollment_completed_at_and_more'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='quiz_ref',
            field=models.ForeignKey(blank=True, help_text="Tham chiếu đến một Quiz nếu type='quiz'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='quiz.quiz'),
        ),
    ]
