# Generated by Django 5.2.5 on 2025-12-19 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_contentblock_quiz_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='current_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_enrollments', to='content.contentblock'),
        ),
    ]
