# Generated by Django 5.2.5 on 2025-12-24 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_enrollment_current_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='current_days_inactive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_engagement_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_performance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_risk_level',
            field=models.CharField(choices=[('low', 'An toàn'), ('medium', 'Cần chú ý'), ('high', 'Rủi ro cao'), ('critical', 'Bỏ học')], db_index=True, default='low', max_length=20),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'current_risk_level'], name='content_enr_course__a9943b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'current_engagement_score'], name='content_enr_course__b3fd22_idx'),
        ),
    ]
