# Generated by Django 5.2.5 on 2025-12-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_enrollment_current_days_inactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cached_completed_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cached_total_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
