# Generated by Django 5.2.5 on 2025-12-19 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Đăng nhập'), ('VIEW_COURSE', 'Xem trang khóa học'), ('VIEW_LESSON', 'Xem bài học'), ('VIDEO_PLAY', 'Bắt đầu xem'), ('VIDEO_PAUSE', 'Tạm dừng'), ('VIDEO_SEEK', 'Tua video'), ('VIDEO_COMPLETE', 'Xem hết video'), ('QUIZ_START', 'Bắt đầu làm bài'), ('QUIZ_SUBMIT', 'Nộp bài'), ('QUIZ_TIMEOUT', 'Hết giờ'), ('SEARCH', 'Tìm kiếm'), ('DOWNLOAD_RESOURCE', 'Tải tài liệu')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='analytics_u_user_id_27edee_idx'), models.Index(fields=['timestamp'], name='analytics_u_timesta_412843_idx')],
            },
        ),
    ]
