# Generated by Django 5.2.5 on 2025-12-19 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('content', '0012_contentblock_quiz_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('performance_score', models.FloatField(default=0.0)),
                ('days_inactive', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'An toàn'), ('medium', 'Cần chú ý'), ('high', 'Rủi ro cao'), ('critical', 'Bỏ học')], db_index=True, max_length=20)),
                ('suggested_action', models.CharField(blank=True, max_length=50)),
                ('ai_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_risks', to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'course', '-created_at'], name='analytics_s_user_id_3a891d_idx'), models.Index(fields=['course', 'risk_level'], name='analytics_s_course__46662b_idx')],
            },
        ),
    ]
