# Generated by Django 5.2.5 on 2025-12-19 10:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_studentrisksnapshot'),
        ('content', '0012_contentblock_quiz_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRiskSnapshot',
            new_name='StudentSnapshot',
        ),
        migrations.RenameIndex(
            model_name='studentsnapshot',
            new_name='analytics_s_user_id_9e7e7b_idx',
            old_name='analytics_s_user_id_3a891d_idx',
        ),
        migrations.RenameIndex(
            model_name='studentsnapshot',
            new_name='analytics_s_course__b52e71_idx',
            old_name='analytics_s_course__46662b_idx',
        ),
    ]
