# Generated by Django 5.2.5 on 2025-12-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_studentrisksnapshot_studentsnapshot_and_more'),
        ('quiz', '0002_alter_quiz_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizStatisticSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_attempts', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('standard_deviation', models.FloatField(default=0.0, help_text='Độ lệch chuẩn')),
                ('median_score', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='quiz.quiz')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionStatisticSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prompt_text_snapshot', models.TextField(blank=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_ratio', models.FloatField(default=0.0)),
                ('discrimination_index', models.FloatField(default=0.0)),
                ('option_distribution', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=20)),
                ('recommendation', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('quiz_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='analytics.quizstatisticsnapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='quizstatisticsnapshot',
            index=models.Index(fields=['quiz', '-calculated_at'], name='analytics_q_quiz_id_058ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='questionstatisticsnapshot',
            index=models.Index(fields=['question', 'quiz_stat'], name='analytics_q_questio_9b46fd_idx'),
        ),
    ]
