# Generated by Django 5.2.5 on 2025-12-20 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_useractivitylog_action'),
        ('content', '0013_enrollment_current_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalyticsLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_students', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại'), ('partial', 'Một phần (Có lỗi nhỏ)')], default='success', max_length=20)),
                ('execution_time_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_logs', to='content.course')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', '-created_at'], name='analytics_c_course__e8d5d2_idx')],
            },
        ),
    ]
