# Generated by Django 5.2.5 on 2025-12-20 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_courseanalyticslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='course_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['course_id', 'timestamp'], name='analytics_u_course__9f6104_idx'),
        ),
    ]
