# Generated by Django 5.2.5 on 2025-12-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_useractivitylog_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Đăng nhập'), ('LOGOUT', 'Đăng xuất'), ('REGISTER', 'Đăng ký tài khoản'), ('UPDATE_PROFILE', 'Cập nhật hồ sơ'), ('VIEW_COURSE', 'Xem trang giới thiệu khóa học'), ('ENROLL', 'Ghi danh khóa học'), ('UNENROLL', 'Hủy ghi danh'), ('COURSE_COMPLETE', 'Hoàn thành khóa học'), ('VIEW_LESSON', 'Xem bài học'), ('LESSON_COMPLETE', 'Hoàn thành bài học'), ('DOWNLOAD_RESOURCE', 'Tải tài liệu đính kèm'), ('VIDEO_PLAY', 'Bắt đầu xem'), ('VIDEO_PAUSE', 'Tạm dừng'), ('VIDEO_SEEK', 'Tua video'), ('VIDEO_COMPLETE', 'Xem hết video'), ('VIDEO_SPEED_CHANGE', 'Đổi tốc độ'), ('LEARNING_SESSION', 'Học được bao lâu'), ('QUIZ_START', 'Bắt đầu làm bài'), ('QUIZ_RESUME', 'Làm tiếp bài đang dở'), ('QUESTION_VIEW', 'Xem câu hỏi'), ('QUESTION_ANSWER_SAVE', 'Lưu nháp câu trả lời'), ('QUIZ_SUBMIT', 'Nộp bài'), ('QUIZ_REVIEW', 'Xem lại bài đã chấm'), ('SEARCH', 'Tìm kiếm'), ('DOWNLOAD_RESOURCE', 'Tải tài liệu'), ('DISCUSSION_POST', 'Đăng thảo luận'), ('NOTE_CREATE', 'Tạo ghi chú'), ('RATING_SUBMIT', 'Đánh giá khóa học'), ('STREAK_UPDATE', 'Cập nhật chuỗi'), ('ITEM_PURCHASE', 'Mua vật phẩm')], db_index=True, max_length=50),
        ),
    ]
