# Generated by Django 5.2.5 on 2025-12-15 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0011_alter_enrollment_options_enrollment_completed_at_and_more'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_mode', models.CharField(choices=[('exam', 'Kiểm tra (Nghiêm ngặt)'), ('practice', 'Ôn luyện (Thoải mái)')], default='exam', max_length=20)),
                ('questions_order', models.JSONField(default=list)),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=10.0)),
                ('is_passed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'Đang làm'), ('submitted', 'Đã nộp'), ('graded', 'Đã chấm điểm')], default='in_progress', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_submitted', models.DateTimeField(blank=True, null=True)),
                ('content_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.contentblock')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='content.enrollment')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(blank=True, choices=[('multiple_choice_single', 'Trắc nghiệm - Chọn 1'), ('multiple_choice_multi', 'Trắc nghiệm - Chọn nhiều'), ('true_false', 'Đúng / Sai'), ('short_answer', 'Trả lời ngắn (Text)'), ('essay', 'Tự luận (Chấm tay)'), ('fill_in_the_blank', 'Điền từ (Cloze)'), ('matching', 'Nối cặp'), ('ordering', 'Sắp xếp thứ tự'), ('numeric', 'Số học')], max_length=50)),
                ('answer_data', models.JSONField(default=dict)),
                ('is_flagged', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='progress.quizattempt')),
            ],
        ),
        migrations.CreateModel(
            name='UserBlockProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('interaction_data', models.JSONField(blank=True, default=dict)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content.contentblock')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_accesses', to='content.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/')),
                ('issued_to_name', models.CharField(help_text='Tên hiển thị trên bằng', max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='content.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_lessons', to='content.enrollment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.lesson')),
            ],
            options={
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='ModuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_modules', to='content.enrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.module')),
            ],
            options={
                'unique_together': {('enrollment', 'module')},
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='progress_qu_user_id_469a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['enrollment'], name='progress_qu_enrollm_14323a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='userblockprogress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='progress_us_enrollm_1a58ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userblockprogress',
            unique_together={('enrollment', 'block')},
        ),
        migrations.AlterUniqueTogether(
            name='usercertificate',
            unique_together={('user', 'course')},
        ),
    ]
