# Generated by Django 5.2.5 on 2025-12-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='attempt_mode',
            field=models.CharField(choices=[('exam', 'Kiểm tra (Nghiêm ngặt)'), ('practice', 'Ôn luyện (Thoải mái)'), ('quiz', 'Quiz')], default='exam', max_length=20),
        ),
    ]
