# Generated by Django 5.2.5 on 2025-12-16 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_contentblock_quiz_ref'),
        ('progress', '0002_alter_quizattempt_attempt_mode'),
        ('quiz', '0002_alter_quiz_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['status'], name='progress_qu_status_d619b2_idx'),
        ),
    ]
