# Generated by Django 5.2.5 on 2025-12-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_questionanswer_is_graded_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercertificate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercertificate',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercertificate',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='usercertificate',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseReview',
        ),
        migrations.DeleteModel(
            name='UserCertificate',
        ),
    ]
