# Generated by Django 5.2.5 on 2025-12-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_alter_usercertificate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblockprogress',
            name='last_logged_time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
