# Generated by Django 5.2.5 on 2025-12-15 08:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề')),
                ('mode', models.CharField(choices=[('exam', 'Kiểm tra (Nghiêm ngặt)'), ('practice', 'Ôn luyện (Thoải mái)')], default='exam', max_length=20)),
                ('time_limit', models.DurationField(blank=True, help_text="Thời gian tối đa cho phép (ví dụ: '00:30:00' cho 30 phút, '01:00:00' cho 1 tiếng)", null=True, verbose_name='Thời lượng làm bài')),
                ('time_open', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian mở')),
                ('time_close', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đóng (hạn chót)')),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Để trống nếu cho làm thoải mái', null=True)),
                ('pass_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('questions_count', models.IntegerField(default=10, help_text='Số lượng câu hỏi hiển thị cho mỗi lần làm bài. 0 = Hiển thị tất cả câu hỏi hiện có.')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Đảo câu hỏi')),
                ('grading_method', models.CharField(choices=[('highest', 'Lấy điểm cao nhất'), ('average', 'Lấy điểm trung bình'), ('first', 'Lấy lần đầu tiên'), ('last', 'Lấy lần cuối cùng')], default='highest', max_length=20)),
                ('show_correct_answer', models.BooleanField(default=True, verbose_name='Hiện đáp án sau khi nộp')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả / Hướng dẫn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài trắc nghiệm',
                'verbose_name_plural': 'Các bài trắc nghiệm',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('multiple_choice_single', 'Trắc nghiệm - Chọn 1'), ('multiple_choice_multi', 'Trắc nghiệm - Chọn nhiều'), ('true_false', 'Đúng / Sai'), ('short_answer', 'Trả lời ngắn (Text)'), ('essay', 'Tự luận (Chấm tay)'), ('fill_in_the_blank', 'Điền từ (Cloze)'), ('matching', 'Nối cặp'), ('ordering', 'Sắp xếp thứ tự'), ('numeric', 'Số học')], default='multiple_choice_single', max_length=50)),
                ('prompt', models.JSONField(blank=True, default=dict, help_text="Nội dung câu hỏi (e.g., {'text': '...', 'image_url': '...'})")),
                ('answer_payload', models.JSONField(blank=True, default=dict, help_text="Cấu hình đáp án, tùy thuộc vào 'type'")),
                ('hint', models.JSONField(blank=True, default=dict, help_text='Gợi ý hoặc giải thích đáp án')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Các câu hỏi',
                'ordering': ['position'],
            },
        ),
    ]
