# Generated by Django 5.2.5 on 2025-11-21 10:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('time_limit', models.DurationField(blank=True, help_text="Thời gian tối đa cho phép (ví dụ: '00:30:00' cho 30 phút, '01:00:00' cho 1 tiếng)", null=True, verbose_name='Thời lượng làm bài')),
                ('time_open', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian mở')),
                ('time_close', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đóng (hạn chót)')),
                ('mode', models.CharField(choices=[('exam', 'Kiểm tra (Nghiêm ngặt)'), ('practice', 'Ôn luyện (Thoải mái)')], default='exam', max_length=20)),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Để trống nếu cho làm thoải mái', null=True)),
                ('pass_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('questions_count', models.IntegerField(default=10, help_text='Số lượng câu hỏi hiển thị cho mỗi lần làm bài. 0 = Hiển thị tất cả câu hỏi hiện có.')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Đảo câu hỏi')),
                ('grading_method', models.CharField(choices=[('highest', 'Lấy điểm cao nhất'), ('average', 'Lấy điểm trung bình'), ('first', 'Lấy lần đầu tiên'), ('last', 'Lấy lần cuối cùng')], default='highest', max_length=20)),
                ('show_correct_answer', models.BooleanField(default=True, verbose_name='Hiện đáp án sau khi nộp')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả / Hướng dẫn')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài trắc nghiệm',
                'verbose_name_plural': 'Các bài trắc nghiệm',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('multiple_choice_single', 'Trắc nghiệm - Chọn 1'), ('multiple_choice_multi', 'Trắc nghiệm - Chọn nhiều'), ('true_false', 'Đúng / Sai'), ('short_answer', 'Trả lời ngắn'), ('fill_in_the_blank', 'Điền vào chỗ trống'), ('matching', 'Nối cặp'), ('essay', 'Tự luận')], default='multiple_choice_single', max_length=50)),
                ('prompt', models.JSONField(blank=True, default=dict, help_text="Nội dung câu hỏi (e.g., {'text': '...', 'image_url': '...'})")),
                ('answer_payload', models.JSONField(blank=True, default=dict, help_text="Cấu hình đáp án, tùy thuộc vào 'type'")),
                ('hint', models.JSONField(blank=True, default=dict, help_text='Gợi ý hoặc giải thích đáp án')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Các câu hỏi',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions_order', models.JSONField(default=list, help_text='Danh sách ID các câu hỏi được chọn ngẫu nhiên cho lần làm bài này')),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_submitted', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('current_question_index', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'Đang làm bài'), ('completed', 'Đã nộp'), ('overdue', 'Quá hạn (Chưa nộp nhưng hết giờ)')], default='in_progress', max_length=20)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_options', models.JSONField(default=dict, help_text='Dữ liệu câu trả lời của user')),
                ('is_correct', models.BooleanField(default=None, null=True)),
                ('score_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
