# Generated by Django 5.2.5 on 2025-11-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_created_at_quiz_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề'),
        ),
    ]
