# Generated by Django 5.2.5 on 2025-11-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_is_flagged_alter_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_flagged',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
