# Generated by Django 5.2.5 on 2025-12-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_is_flagged_useranswer_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple_choice_single', 'Trắc nghiệm - Chọn 1'), ('multiple_choice_multi', 'Trắc nghiệm - Chọn nhiều'), ('true_false', 'Đúng / Sai'), ('short_answer', 'Trả lời ngắn (Text)'), ('essay', 'Tự luận (Chấm tay)'), ('fill_in_the_blank', 'Điền từ (Cloze)'), ('matching', 'Nối cặp'), ('ordering', 'Sắp xếp thứ tự'), ('numeric', 'Số học')], default='multiple_choice_single', max_length=50),
        ),
    ]
