# Generated by Django 5.2.5 on 2025-11-05 10:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Detailed instructions for students')),
                ('assignment_type', models.CharField(choices=[('homework', 'Homework'), ('quiz', 'Quiz'), ('project', 'Project'), ('worksheet', 'Worksheet'), ('essay', 'Essay')], default='homework', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum possible score', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum score to pass', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('allow_late_submissions', models.BooleanField(default=True)),
                ('late_penalty_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage penalty per day late', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maximum number of submission attempts (0 = unlimited)')),
                ('is_group_assignment', models.BooleanField(default=False, help_text='Whether this is a group assignment')),
                ('auto_grade', models.BooleanField(default=False, help_text='Whether to automatically grade submissions')),
                ('requires_parent_consent', models.BooleanField(default=False)),
                ('age_appropriate_level', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('classroom', models.ForeignKey(blank=True, help_text='The classroom this assignment is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='school.classroommodel')),
                ('lesson', models.ForeignKey(blank=True, help_text='The lesson this assignment is linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='content.lesson')),
                ('teacher', models.ForeignKey(blank=True, help_text='The teacher who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('content', models.TextField(blank=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignment_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('late_penalty_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('letter_grade', models.CharField(blank=True, max_length=5)),
                ('feedback', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assignments.submission')),
            ],
            options={
                'db_table': 'assignment_grades',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'due_date'], name='assignments_status_a60348_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['classroom', 'status'], name='assignments_classro_fa9f43_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['teacher', 'created_at'], name='assignments_teacher_3b1adb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'status'], name='assignment__assignm_68808b_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='assignment__student_e9c2f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student', 'attempt_number')},
        ),
    ]
