# Generated by Django 5.2.5 on 2025-12-17 17:56

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0012_contentblock_quiz_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=1536)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='content.course')),
            ],
            options={
                'verbose_name': 'Course Embedding',
                'verbose_name_plural': 'Course Embeddings',
            },
        ),
    ]
