# Generated by Django 5.2.5 on 2025-12-17 22:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0002_alter_courseembedding_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseembedding',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=1536),
        ),
    ]
