# Generated by Django 5.2.5 on 2025-11-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
