# Generated by Django 5.2.5 on 2025-11-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_uploadedfile_delete_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
