# Generated by Django 5.2.5 on 2025-11-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_uploadedfile_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
