# Generated by Django 5.2.5 on 2025-11-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_uploadedfile_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='component',
            field=models.CharField(blank=True, choices=[('course_thumbnail', 'Ảnh bìa khóa học'), ('user_avatar', 'Avatar người dùng'), ('site_logo', 'Logo trang web'), ('public_attachment', 'File đính kèm công khai'), ('lesson_material', 'Tài liệu bài học'), ('quiz_attachment', 'File trong đề thi'), ('submission_file', 'Bài nộp của học viên')], db_index=True, max_length=100, null=True),
        ),
    ]
