# Generated by Django 5.2.5 on 2025-09-01 11:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exploration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(db_index=True, max_length=200)),
                ('objective', models.TextField(default='')),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), db_index=True, default=list, size=None)),
                ('version', models.IntegerField(default=1)),
                ('owners', models.ManyToManyField(related_name='exploration_owners', to='account.user')),
            ],
        ),
    ]
