# Generated by Django 5.2.5 on 2025-09-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exploration',
            name='owners',
        ),
    ]
