name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2 and deploy backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/e-learning
            git pull origin main
            source venv/bin/activate
            pip install -r backend/requirements.txt
            python backend/manage.py migrate --noinput
            python backend/manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
